package org.example;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.*;


public class FormsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\hanss\\Desktop\\sda\\Kody\\Selenium\\src\\main\\resources\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void forms() {
    // Test name: Forms
    // Step # | name | target | value
    // 1 | open | https://www.tutorialspoint.com/selenium/selenium_automation_practice.htm | 
    driver.get("https://www.tutorialspoint.com/selenium/selenium_automation_practice.htm");
    // 2 | setWindowSize | 1936x1048 | 
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.xpath("/html/body/div[2]/div[2]/div[1]/div[2]/div[2]/button[1]")).click();

    // 3 | click | name=firstname | 
    driver.findElement(By.name("firstname")).click();
    // 4 | type | name=firstname | Jan
    driver.findElement(By.name("firstname")).sendKeys("Jan");
    // 5 | click | name=lastname | 
    driver.findElement(By.name("lastname")).click();
    // 6 | type | name=lastname | Sima
    driver.findElement(By.name("lastname")).sendKeys("Sima");
    // 7 | click | name=sex | 
    driver.findElement(By.name("sex")).click();
    // 8 | click | css=span:nth-child(5) > input | 
    driver.findElement(By.cssSelector("span:nth-child(5) > input")).click();
    // 9 | type | xpath=/html/body/main/div/div/div[2]/div[3]/div/form/div/table/tbody/tr[5]/td[2]/input | 11.06.1993
    driver.findElement(By.xpath("/html/body/main/div/div/div[2]/div[3]/div/form/div/table/tbody/tr[5]/td[2]/input")).sendKeys("11.06.1993");
    // 10 | click | css=tr:nth-child(6) span:nth-child(2) > input | 
    driver.findElement(By.cssSelector("tr:nth-child(6) span:nth-child(2) > input")).click();
    // 11 | click | name=photo | 
    //driver.findElement(By.name("photo")).click();
    // 12 | click | css=tr:nth-child(8) span:nth-child(2) > input | 
    driver.findElement(By.cssSelector("tr:nth-child(8) span:nth-child(2) > input")).click();
    // 13 | click | name=continents | 
    driver.findElement(By.name("continents")).click();
    // 14 | addSelection | name=selenium_commands | label=Wait Commands
    {
      WebElement dropdown = driver.findElement(By.name("selenium_commands"));
      dropdown.findElement(By.xpath("//option[. = 'Wait Commands']")).click();
    }
    // 15 | click | css=tr:nth-child(10) option:nth-child(4) | 
    driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(4)")).click();
    // 16 | click | css=tr:nth-child(10) option:nth-child(4) | 
    driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(4)")).click();
    // 17 | doubleClick | css=tr:nth-child(10) option:nth-child(4) | 
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    // 21 | click | name=submit | 
    vars.put("window_handles", driver.getWindowHandles());
    // 22 | assertConfirmation | You are submitting information to an external page.
    driver.findElement(By.name("submit")).click();
    // 23 | webdriverChooseOkOnVisibleConfirmation |  | 
    vars.put("win3541", waitForWindow(2000));
    // 24 | selectWindow | handle=${win3541} | 
    // 25 | close |  |
    driver.switchTo().alert().accept();
    driver.switchTo().window(vars.get("win3541").toString());
    driver.close();
  }
}
